# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd3cfa42461f5350ec20c501e3ea2f2d63422a6b8517296da763036a6a720db4a6b12de32d26e828a448112a39c68646a6112e1fae7093cf943e7af2813d2bc8

test:
  secret_key_base: eb0571392d702d9401d4a42423da7f4650ee9460a2572e69207a9c685a53e3ab3b2dee50798dac81bf4f4f950c7cbd46a894940818c54ac26359f1225628300f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
